############################
## Author
############################

author:
  name: "State of the Map Asia"
  image: author.png
  greeting: "Stay Connected with State of the Map Asia 🗺️🌏️"
  icon: "🔗"

############################
## Links
############################

links:
  - website: https://stateofthemap.asia/
  - github: https://github.com/sotm-asia/
  - instagram: https://www.instagram.com/stateofthemap_asia/
  - x-twitter: https://x.com/SotmAsia/
  - mastodon: https://en.osm.town/@sotmasia/
  - telegram: https://t.me/+nUCQpqtFzy84ZmY1
  - email: stateofthemapasia@gmail.com
  - linkedin: https://www.linkedin.com/company/state-of-the-map-asia/
  - link: https://lists.openstreetmap.org/listinfo/talk-asia/ # mailing list
  - link: https://www.facebook.com/SotmAsia/ # Facebook


  # - reddit: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 3

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: true

###############################
## OpenGraph & Twitter Cards
###############################

title: "State of the Map Asia Socail Links"
description: "All social media links for State of the Map Asia"
images:
  - thumbnail.png
